name: company
services:
    json-data-server-api:
        environment:
            CONFIG_BUCKET_NAME: ${CONFIG_BUCKET_NAME}
            CONFIG_KEY: ${CONFIG_KEY}
            AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
            AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
            AWS_REGION: ${AWS_REGION}
        container_name: json-data-server-api
        build:
            context: .
        ports:
            - '8087:80'
